{ pkgs, ... }:

{ environment.systemPackages = with pkgs; [
      cudaPackages.nvidia_driver
      spice
      spice-gtk
      spice-vdagent
      open-vm-tools
      guestfs-tools
      virglrenderer
      x11spice
      docker-client
      docker
      docker-compose
      docker-machine-kvm
      docker-machine-kvm2
      x11docker
      podman
      podman-desktop
      skopeo
      buildah
      terminator
      dotnet-sdk
      vscode-with-extensions
      vscodium
      brave
      firefox
      htop
      ranger
      fish
      vim
      wget
      w3m
      dmenu
      neofetch
      neovim
      starship
      bash
      bash-completion
      bashSnippets
      bat
      bazecor
      cargo
      celluloid
      chatterino2
      clang-tools_9
      dunst
      efibootmgr
      elinks
      eww
      feh
      flameshot
      flatpak
      floorp
      fontconfig
      freetype
      fuse-common
      gcc
      gimp
      git
      github-desktop
      gnome.gnome-keyring
      gnugrep
      gnumake
      gparted
      gnugrep
      grub2
      hugo
      kitty
      libverto
      luarocks
      lxappearance
      mangohud
      neovim
      nfs-utils
      ninja
      nodejs
      nomacs
      openssl
      os-prober
      nerdfonts
      pavucontrol
      picom
      polkit_gnome
      powershell
      protonup-ng
      python3Full
      python.pkgs.pip
      qemu
      ripgrep
      rofi
      steam
      steam-run
      sxhkd
      st
      stdenv
      synergy
      swaycons
      terminus-nerdfont
      tldr
      trash-cli
      unzip
      variety
      virt-manager
      xclip
      xdg-desktop-portal-gtk
      xfce.thunar
      xorg.libX11
      xorg.libX11.dev
      xorg.libxcb
      xorg.libXft
      xorg.libXinerama
      xorg.xinit
      xorg.xinput
      zoxide
  ];
}


      

